name=MtN1
version=1.0.0
author=Turtlerock0010
maintainer=Daniel Principe (turtlerock0010@gmail.com)
sentence=The mini robotics control library for the MtN1 (Motion-1).
paragraph=Supports motors, servos, and GPIO. Simplifies MtN1 control for the end user.
category=Device Control
url=https://github.com/Turtlerock0010/MtN1-Lib
architectures=*
